import{supabase}from'./supabase.js?v=20260829-11';
const postingFields=[['blog_sloom','슬룸'],['blog_modoo','모두'],['blog_main','메인'],['cafe','카페'],['wordpress','워드프레스'],['threads','스레드'],['instagram','인스타'],['youtube','유튜브'],['carrot','당근'],['openchat','오픈채팅'],['qa','질의응답'],['knowledge','지식인'],['meeting','미팅']];
const today=()=>{const date=new Date(),offset=date.getTimezoneOffset()*60000;return new Date(date-offset).toISOString().slice(0,10)};
export async function activityPage(root,me){
  root.innerHTML=`<section class="card"><h2>일일업무일지</h2><label>기록할 날짜<input id="activityDate" type="date" value="${today()}"></label></section><section class="activity-hero"><span>오늘 개통</span><b id="activationTotal">0건</b></section><form id="activityForm"><section class="card"><div class="section-head"><h2>포스팅 / SNS 기록</h2><b id="postingTotal">총 0건</b></div><div class="activity-grid">${postingFields.map(([key,label])=>`<label>${label}<input type="number" min="0" value="0" data-posting="${key}"></label>`).join('')}</div></section><section class="card"><h2>개통·매출 기록</h2><div class="activity-grid two"><label>신규개통양도금(원)<input id="newTransfer" type="number" min="0" value="0"></label><label>재구매요금양도금(원)<input id="repurchase" type="number" min="0" value="0"></label><label>현재요금잔액(원)<input id="balance" type="number" min="0" value="0"></label><label>앤보임 수강생<input id="attendance" type="number" min="0" value="0"></label><label>A 자동매출(NV)<input id="aSales" type="number" min="0" value="0"></label><label>B 자동매출(NV)<input id="bSales" type="number" min="0" value="0"></label></div></section><section class="card"><h2>오늘 할 일</h2><div class="task-list">${Array.from({length:10},(_,i)=>`<label><span>${i+1}</span><input data-task="${i}" placeholder="예: 앤텔고객 충전"></label>`).join('')}</div></section><button class="primary activity-save" type="submit">이 날짜 기록 저장</button><div id="activityStatus" class="connection-status" hidden></div><div id="activityError" class="error"></div></form>`;
  const $=id=>document.getElementById(id),number=id=>Number($(id).value||0),postingInputs=[...root.querySelectorAll('[data-posting]')],taskInputs=[...root.querySelectorAll('[data-task]')];
  const totals=()=>{$('postingTotal').textContent=`총 ${postingInputs.reduce((sum,input)=>sum+Number(input.value||0),0)}건`};postingInputs.forEach(input=>input.oninput=totals);
  async function load(){const date=$('activityDate').value,[record,activations]=await Promise.all([supabase.from('daily_activities').select('*').eq('owner_id',me.id).eq('activity_date',date).maybeSingle(),supabase.from('customers').select('*',{count:'exact',head:true}).eq('owner_id',me.id).eq('activation_date',date)]),{data,error}=record;if(error){$('activityError').textContent=error.message;return}$('activationTotal').textContent=`${activations.count||0}건`;const content=data?.content||{},posts=content.postings||{};postingInputs.forEach(input=>input.value=posts[input.dataset.posting]||0);$('newTransfer').value=data?.new_transfer||0;$('repurchase').value=data?.repurchase||0;$('balance').value=data?.balance||0;$('attendance').value=data?.attendance||0;$('aSales').value=data?.a_sales||0;$('bSales').value=data?.b_sales||0;taskInputs.forEach((input,i)=>input.value=(data?.tasks||[])[i]||'');totals();$('activityStatus').hidden=!data;if(data){$('activityStatus').textContent='저장된 기록을 불러왔습니다.'}}
  $('activityDate').onchange=load;$('activityForm').onsubmit=async event=>{event.preventDefault();$('activityError').textContent='';const postings=Object.fromEntries(postingInputs.map(input=>[input.dataset.posting,Number(input.value||0)])),value={owner_id:me.id,activity_date:$('activityDate').value,new_transfer:number('newTransfer'),repurchase:number('repurchase'),balance:number('balance'),attendance:number('attendance'),a_sales:number('aSales'),b_sales:number('bSales'),tasks:taskInputs.map(input=>input.value.trim()),content:{postings},updated_at:new Date().toISOString()},{error}=await supabase.from('daily_activities').upsert(value,{onConflict:'owner_id,activity_date'});if(error)$('activityError').textContent=error.message;else{$('activityStatus').hidden=false;$('activityStatus').textContent='이 날짜의 기록을 저장했습니다.'}};await load();
}
