import{supabase,signUp,signIn,currentProfile}from'./supabase.js';
const $=id=>document.getElementById(id);let me=null,authMode='login';const menus=[['home','홈'],['customers','고객'],['activity','활동'],['organization','조직'],['performance','실적'],['commission','수당'],['closing','마감'],['settings','설정']];
function nav(){const html=menus.map(([id,label])=>`<button data-page="${id}">${label}</button>`).join('');$('topNav').innerHTML=html;$('bottomNav').innerHTML=menus.slice(0,4).concat([['more','더보기']]).map(([id,label])=>`<button data-page="${id}">${label}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page))}
function home(){const frag=$('homeTemplate').content.cloneNode(true);$('content').replaceChildren(frag);$('monthlySummary').textContent='개통 0건 · 신규 0건 · 재구매 0건 · 매출 0원'}
async function show(page){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='home')return home();if(page==='settings'){$('content').innerHTML='<section class="card"><h2>설정</h2><button class="primary" id="logout">로그아웃</button></section>';$('logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};return}$('content').innerHTML=`<section class="card"><h2>${menus.find(x=>x[0]===page)?.[1]||'더보기'}</h2><p>기획서 기준 모듈을 순서대로 연결 중입니다.</p></section>`}
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';$('signupNameWrap').hidden=!signup;$('signupName').required=signup;$('authDescription').textContent=signup?'회원번호로 새 계정을 만드세요.':'회원번호와 비밀번호로 로그인하세요.';$('authSubmit').textContent=signup?'회원가입':'로그인';$('authModeBtn').textContent=signup?'이미 계정이 있나요? 로그인':'처음이신가요? 회원가입'}
async function start(){me=await currentProfile();if(!me)return;$('loginView').hidden=true;$('appView').hidden=false;$('userName').textContent=`${me.name}님`;nav();show('home')}
$('authModeBtn').onclick=()=>setAuthMode(authMode==='login'?'signup':'login');
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';const memberNo=$('loginMemberNo').value.trim(),password=$('loginPassword').value;try{if(authMode==='signup')await signUp({memberNo,name:$('signupName').value.trim(),password});else await signIn({memberNo,password});await start()}catch(err){$('loginError').textContent=err.message}};
$('refreshBtn').onclick=()=>show('home');if(!supabase){$('loginError').textContent='Supabase publishable key 설정이 필요합니다.'}else{supabase.auth.getSession().then(({data})=>{if(data.session)start().catch(()=>{})})}
