import{supabase,signUp,signIn,currentProfile}from'./supabase.js?v=20260829-3';
const $=id=>document.getElementById(id);let me=null,authMode='login';const menus=[['home','홈'],['customers','고객'],['activity','활동'],['organization','조직'],['performance','실적'],['commission','수당'],['closing','마감'],['settings','설정']];
function nav(){const html=menus.map(([id,label])=>`<button data-page="${id}">${label}</button>`).join('');$('topNav').innerHTML=html;$('bottomNav').innerHTML=menus.slice(0,4).concat([['more','더보기']]).map(([id,label])=>`<button data-page="${id}">${label}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page))}
function home(){const frag=$('homeTemplate').content.cloneNode(true);$('content').replaceChildren(frag);$('monthlySummary').textContent='개통 0건 · 신규 0건 · 재구매 0건 · 매출 0원'}
async function show(page){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='home')return home();if(page==='settings'){$('content').innerHTML='<section class="card"><h2>설정</h2><button class="primary" id="logout">로그아웃</button></section>';$('logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};return}$('content').innerHTML=`<section class="card"><h2>${menus.find(x=>x[0]===page)?.[1]||'더보기'}</h2><p>기획서 기준 모듈을 순서대로 연결 중입니다.</p></section>`}
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';$('authDescription').textContent=signup?'아이디와 비밀번호만 정하면 가입됩니다.':'아이디와 비밀번호로 로그인하세요.';$('authSubmit').textContent=signup?'회원가입':'로그인';$('authModeBtn').textContent=signup?'이미 계정이 있나요? 로그인':'처음이신가요? 회원가입';$('loginPassword').autocomplete=signup?'new-password':'current-password'}
async function start(){me=await currentProfile();if(!me)return;$('loginView').hidden=true;$('appView').hidden=false;$('userName').textContent=`${me.name||me.username}님`;nav();show('home')}
$('authModeBtn').onclick=()=>setAuthMode(authMode==='login'?'signup':'login');
$('loginForm').onsubmit=async e=>{e.preventDefault();const errorBox=$('loginError'),submit=$('authSubmit'),username=$('loginUsername').value.trim(),password=$('loginPassword').value;errorBox.textContent='';submit.disabled=true;submit.textContent=authMode==='signup'?'가입 중...':'로그인 중...';try{if(authMode==='signup'){try{const result=await signUp({username,password});if(!result.session)await signIn({username,password})}catch(err){if(/already registered/i.test(err.message))await signIn({username,password});else throw err}}else await signIn({username,password});await start()}catch(err){errorBox.textContent=/invalid login credentials/i.test(err.message)?'아이디 또는 비밀번호가 맞지 않습니다.':/email not confirmed/i.test(err.message)?'관리자 설정에서 이메일 확인을 꺼주세요.':err.message}finally{submit.disabled=false;submit.textContent=authMode==='signup'?'회원가입':'로그인'}};
$('refreshBtn').onclick=()=>show('home');if(!supabase){$('loginError').textContent='Supabase publishable key 설정이 필요합니다.'}else{supabase.auth.getSession().then(({data})=>{if(data.session)start().catch(()=>{})})}
