import{supabase}from'./supabase.js?v=20260829-11';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function customersPage(root,me){
  root.innerHTML=`<section class="card"><div class="section-head"><div><h2>고객 관리</h2><p class="help">내 고객과 공유 허용된 팀 고객을 관리합니다.</p></div><button class="primary compact" id="customerAdd">+ 고객 등록</button></div><div class="view-tabs"><button class="active" data-scope="mine">내 고객</button><button data-scope="shared">공유 고객</button></div><div class="customer-tools"><input id="customerSearch" type="search" placeholder="이름·전화번호·회원번호 검색"><select id="customerNetwork"><option value="">전체 통신사</option><option>KT</option><option>LG U+</option><option>SKT</option><option>알뜰폰</option></select></div><div id="customerSummary" class="org-summary"></div><div id="customerError" class="error"></div><div id="customerList" class="customer-list"></div></section><dialog id="customerDialog" class="customer-dialog"><form id="customerForm"><div class="dialog-head"><h2 id="customerTitle">고객 등록</h2><button id="customerClose" type="button">×</button></div><div class="customer-form"><input id="cId" type="hidden"><label>개통일<input id="cDate" type="date"></label><label>회원번호<input id="cMember"></label><label>고객명<input id="cName" required></label><label>전화번호<input id="cPhone" type="tel"></label><label>통신사<select id="cNetwork"><option value="">선택</option><option>KT</option><option>LG U+</option><option>SKT</option><option>알뜰폰</option></select></label><label>요금제<input id="cPlan"></label><label>개통유형<select id="cType"><option>신규</option><option>번호이동</option><option>기기변경</option></select></label><label>개통방법<select id="cMethod"><option>플랫폼</option><option>앤스마트</option><option>지점방문</option></select></label><label>유입경로<input id="cSource"></label><label>기여도<input id="cAttribution" type="number" min="0" value="0"></label><label class="full">메모<textarea id="cMemo" rows="3"></textarea></label></div><div class="customer-actions"><button class="secondary" id="customerCancel" type="button">취소</button><button class="primary" type="submit">저장</button></div></form></dialog>`;
  const $=id=>document.getElementById(id),dialog=$('customerDialog');let rows=[],scope='mine';
  const render=()=>{const q=$('customerSearch').value.trim().toLowerCase(),network=$('customerNetwork').value;const shown=rows.filter(r=>(scope==='mine'?r.owner_id===me.id:r.owner_id!==me.id)&&(!network||r.network===network)&&(!q||[r.name,r.phone,r.member_no].some(v=>String(v||'').toLowerCase().includes(q))));$('customerSummary').innerHTML=`<article><span>표시 고객</span><b>${shown.length}명</b></article><article><span>KT</span><b>${shown.filter(r=>r.network==='KT').length}명</b></article><article><span>LG U+</span><b>${shown.filter(r=>r.network==='LG U+').length}명</b></article>`;$('customerList').innerHTML=shown.length?shown.map(r=>`<article class="customer-item"><button class="customer-main" data-edit="${esc(r.id)}"><b>${esc(r.name)}</b><small>${esc(r.phone||'전화번호 없음')} · ${esc(r.network||'통신사 미지정')} ${esc(r.plan||'')}</small><small>${esc(r.activation_date||'개통일 없음')} · ${esc(r.activation_type||'신규')} · ${r.owner_id===me.id?'내 고객':'공유 고객'}</small>${r.memo?`<span>${esc(r.memo)}</span>`:''}</button>${r.owner_id===me.id?`<button class="customer-delete" data-delete="${esc(r.id)}">삭제</button>`:''}</article>`).join(''):'<p class="help">표시할 고객이 없습니다.</p>';root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(rows.find(r=>r.id===b.dataset.edit)));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete))};
  const open=r=>{const edit=!r||r.owner_id===me.id;$('customerTitle').textContent=r?(edit?'고객 정보 수정':'공유 고객 상세'):'고객 등록';const values={cId:r?.id,cDate:r?.activation_date,cMember:r?.member_no,cName:r?.name,cPhone:r?.phone,cNetwork:r?.network,cPlan:r?.plan,cType:r?.activation_type||'신규',cMethod:r?.activation_method||'플랫폼',cSource:r?.source,cAttribution:r?.attribution||0,cMemo:r?.memo};Object.entries(values).forEach(([id,v])=>$(id).value=v||'');dialog.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=!edit);dialog.querySelector('[type=submit]').hidden=!edit;dialog.showModal()};
  async function load(){const{data,error}=await supabase.from('customers').select('*').order('activation_date',{ascending:false,nullsFirst:false});if(error){$('customerError').textContent=error.message;return}rows=data||[];render()}
  async function remove(id){if(!confirm('고객 정보를 삭제할까요?'))return;const{error}=await supabase.from('customers').delete().eq('id',id);if(error)$('customerError').textContent=error.message;else load()}
  $('customerAdd').onclick=()=>open();$('customerClose').onclick=$('customerCancel').onclick=()=>dialog.close();$('customerSearch').oninput=$('customerNetwork').onchange=render;root.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{scope=b.dataset.scope;root.querySelectorAll('[data-scope]').forEach(x=>x.classList.toggle('active',x===b));render()});$('customerForm').onsubmit=async e=>{e.preventDefault();const id=$('cId').value,value={owner_id:me.id,activation_date:$('cDate').value||null,member_no:$('cMember').value||null,name:$('cName').value.trim(),phone:$('cPhone').value||null,network:$('cNetwork').value||null,plan:$('cPlan').value||null,activation_type:$('cType').value,activation_method:$('cMethod').value,source:$('cSource').value||null,attribution:Number($('cAttribution').value||0),memo:$('cMemo').value||null,updated_at:new Date().toISOString()};const{error}=id?await supabase.from('customers').update(value).eq('id',id):await supabase.from('customers').insert(value);if(error)$('customerError').textContent=error.message;else{dialog.close();load()}};await load();
}
